spring:
  application:
    name: project2
  profiles:
    active: dev
    group:
      dev:
        - db
        - ai
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:application-auth.yml
