spring:
  application:
    name: project2

  profiles:
    active: dev

    group:
      dev:
        - ai
        - auth
        - db

  config:
    import: optional:file:.env[.properties]

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      # 외부 또는 운영 Redis 사용하기 시작할 때 추가 사항
#      username: ${REDIS_USERNAME:}
#      password: ${REDIS_PASSWORD:}
#      database: 0
#      timeout: 3s
#      ssl:
#        enabled: false

app:
  kakao:
    rest-api-key: ${KAKAO_REST_API_KEY:}
  matching:
    waiting-ttl: 5m
    default-search-radius-meters: 3000
