spring:
  application:
    name: project2

  profiles:
    active: dev

    group:
      dev:
        - ai
        - auth
        - db

  config:
    import: optional:file:.env[.properties]

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
